"""Fixed reference values: published examples and independent 50-digit arithmetic.

See docs/pvt_phase_2.md for provenance, equation variants and reference inputs.
Expected values are constants, never generated by calling implementation code.
"""
import pytest
from material_balance_studio.pvt.fluid import fluid_from_inputs, BlackOilFluid
from material_balance_studio.pvt.correlations.base import CorrelationInput
from material_balance_studio.pvt.correlations.registry import REGISTRY
from material_balance_studio.pvt.correlations.gas_z import dak_z, sutton_pseudocritical
from material_balance_studio.pvt.correlations.oil_viscosity import beggs_robinson_dead, beggs_robinson_live, undersaturated_viscosity
from material_balance_studio.pvt.correlations.solution_gor import vasquez_beggs_rs
from material_balance_studio.pvt.correlations.bubble_point import vasquez_beggs_pb
from material_balance_studio.pvt.correlations.oil_fvf import vasquez_beggs_bo
from material_balance_studio.units.conversions import to_si
from material_balance_studio.units.temperature import temperature_to_kelvin, temperature_from_kelvin


@pytest.mark.parametrize("key,expected,quantity", [
    ("standing_pb", 2113.543928855771, "pressure"),
    ("vasquez_beggs_pb", 2366.736834072329, "pressure"),
    ("glaso_pb", 2451.815344319128, "pressure"),
    ("standing_rs", 610.7613681303263, "rs"),
    ("vasquez_beggs_rs", 533.5913496932905, "rs"),
    ("glaso_rs", 511.6207937670833, "rs"),
    ("standing_bo", 1.292949195140943, "bo"),
    ("vasquez_beggs_bo", 1.2988436, "bo"),
    ("glaso_bo", 1.258464495419306, "bo"),
    ("beggs_robinson_mu", .6398767305448119, "viscosity"),
    ("mccain_bw", 1.028363968194184, "bw"),
])
def test_registry_fixed_reference(key, expected, quantity):
    f = fluid_from_inputs(api=35, gas_gravity=.75, temperature=180, initial_pressure=2500, rsb=500, units="FIELD")
    inputs = CorrelationInput(f, to_si(2500, "pressure", "FIELD"), to_si(500, "rs", "FIELD"))
    assert REGISTRY[key].evaluate(inputs) == pytest.approx(to_si(expected, quantity, "FIELD"), rel=2e-12)


def test_dak_published_example_and_registry_boundary():
    # GasCompressibility-py DAK example Pr=3.1995, Tr=1.5006.
    assert dak_z(3.1995, 1.5006) == pytest.approx(.7730934971021096, rel=2e-10)
    # Phase 2.1 audit: Sutton (1985), Eq. 14 uses 131.0, not the library's
    # 131.07. Thus SG=.7 gives 663.336 psia. Original paper:
    # https://yacsgas.wordpress.com/wp-content/uploads/2013/03/00014265.pdf
    assert sutton_pseudocritical(.7) == pytest.approx((663.336, 377.59))
    f = BlackOilFluid(35, .7, 1.5006*377.59/1.8, to_si(3.1995*663.336, "pressure", "FIELD"))
    assert REGISTRY["sutton_dak_z"].evaluate(CorrelationInput(f, f.initial_pressure)) == pytest.approx(.7730934971021096, rel=2e-10)


def test_real_gas_fvf_reference_standard_state():
    f = BlackOilFluid(35, .75, 288.7055555555555, 101325)
    assert REGISTRY["real_gas_bg"].evaluate(CorrelationInput(f, 101325, z=1)) == pytest.approx(1)
    assert REGISTRY["real_gas_bg"].evaluate(CorrelationInput(f, 101325*10, z=.8)) == pytest.approx(.08)


def test_compressibility_published_example():
    # Pengtools: Rs=53.24 SI, T=363 K, oil SG=.85, gas SG=.75, p=10 MPa.
    f = BlackOilFluid(141.5/.85-131.5, .75, 363, 10e6)
    value = REGISTRY["vasquez_beggs_co"].evaluate(CorrelationInput(f, 10e6, rs=53.24))
    assert value*1e6 == pytest.approx(.002907, abs=1e-6)  # rounded source solution
    assert value*1e6 == pytest.approx(.002907667529411765, rel=1e-12)  # independent decimal arithmetic


def test_viscosity_published_rounded_example():
    # Source lists rounded .922 SG or 22 API. API-derived SG avoids truncation;
    # its worked solution is itself rounded. Exact formulation tested above.
    sg = 141.5/(22+131.5)
    assert beggs_robinson_dead(137, sg) == pytest.approx(17.44, abs=.03)
    assert beggs_robinson_live(90, 137, sg) == pytest.approx(8.24, abs=.02)
    assert undersaturated_viscosity(1.2, 4000, 2500) == pytest.approx(1.409550354932235, rel=1e-12)


@pytest.mark.parametrize("api", [25., 30., 30.00001, 45.])
def test_vb_two_api_regimes_invert_without_rounded_coefficients(api):
    rs = vasquez_beggs_rs(2500, 180, api, .75)
    assert vasquez_beggs_pb(rs, 180, api, .75) == pytest.approx(2500, rel=1e-12)
    # Independent arithmetic on the low-API Bo coefficients at the branch boundary.
    if api == 30:
        assert vasquez_beggs_bo(500, 180, api, .75) == pytest.approx(1.274434)


@pytest.mark.parametrize("value,units,kelvin", [(0,"SI",273.15), (100,"SI",373.15), (32,"FIELD",273.15), (212,"FIELD",373.15)])
def test_temperature_units(value, units, kelvin):
    assert temperature_to_kelvin(value, units) == pytest.approx(kelvin)
    assert temperature_from_kelvin(kelvin, units) == pytest.approx(value)


@pytest.mark.parametrize("key", list(REGISTRY))
def test_every_registered_equation_has_traceable_metadata(key):
    entry = REGISTRY[key]
    assert entry.reference.startswith("https://") and entry.formulation and entry.property and entry.name
